#!/bin/bash

##############################################################################
# Options:
#   -P PE reads as input (default)
#   -S SE reads as input
#   -I input SAM file name (required; generated by BWA-MEM)
#   -O output circRNA list name (required)
#   -A input GTF/GFF formatted annotation file name (optional)
#   -R directory of reference sequence(s). Please make sure files in this directory are from the FASTA file(s) provided to BWA-MEM. Either this argument or --ref-file/-F is required for splicing signal searching.
#   -F FASTA file of all reference sequences. Please make sure this file is the same one provided to BWA-MEM. Either this argument or --ref-dir/-R is required for splicing signal searching.
#   -M max spanning distance (default: 500,000)
##############################################################################
while getopts ":I:O:A:R:F:M:" opt; do
  case $opt in
    I)
    O)
    A)
    R)
    F)
    M)
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
		: ) echo "Option -$OPTARG requires an argument." >&2; exit 2;;
	esac
done

#### Check parameters ####



#### circRNA identification ####
perl CIRI.pl -P
