#!/bin/bash

##############################################################################
# Options:
#   -a input GTF/GFF formatted annotation file name (optional)
#   -i input SAM file name (required; generated by BWA-MEM)
#   -s sequencing strategy (single-end or paired-end)
#   -o output circRNA list name (required)
#   -f FASTA file of all reference sequences.
#   -m max spanning distance (default: 500,000)
##############################################################################
while getopts ":a:i:s:o:f:m:" opt; do
  case $opt in
    a) GTF_FILE=$OPTARG ;;
    i) INPUT_SAM_FILE=$OPTARG ;;
    s) STRATEGY=$OPTARG ;;
    o) OUTPUT=$OPTARG ;;
    f) FASTA_FILE=$OPTARG ;;
    m) SPANNING=$OPTARG ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
		: ) echo "Option -$OPTARG requires an argument." >&2; exit 2;;
  esac
done

#### Check parameters ####
# Check GTF annotation files
if [ -z $GTF_FILE ] || [ ! -f $GTF_FILE ]; then
	echo "Annotation file does not exist!"
	exit 3
fi

# Check input files
if [ -z $INPUT_SAM_FILE ] || [ ! -f $INPUT_SAM_FILE ]; then
	echo "Input file does not exist!" >&2
	exit 4
fi

# Control sequencing strategy "single end" o "paired end"
if [ $STRATEGY = "single" ]; then
	PAIRED=false
elif [ $STRATEGY = "paired" ]; then
  PAIRED=true
else
  echo "error with select the sequencing strategy" >&2
	exit 5
fi

# Check output
if [ -z $OUTPUT ]; then
	echo "Output file must be specified!" >&2
	exit 6
fi

# Check if output directory is writable
if [ ! -w $(dirname $OUTPUT) ]; then
	echo "Output directory is not writable!" >&2
	exit 7
fi

# Check fasta file
if [ -z $FASTA_FILE ] || [ ! -f $FASTA_FILE ]; then
	echo "FASTA file does not exist!"
	exit 8
fi

# Check max spanning distance (default: 500,000)
if [ -z $SPANNING ]; then
	SPANNING=500000
fi

#### circRNA identification ####
SAMPLE_NAME=$(basename $INPUT_SAM_FILE ".sam")
SUFF="_ciri.txt"
OUTPUT_NAME=$SAMPLE_NAME$SUFF

if [ $PAIRED ]; then
  perl CIRI.pl -I $INPUT_SAM_FILE -A $GTF_FILE -F $FASTA_FILE -M $SPANNING -o $OUTPUT/$OUTPUT_NAME -P
else
  perl CIRI.pl -I $INPUT_SAM_FILE -A $GTF_FILE -F $FASTA_FILE -M $SPANNING -o $OUTPUT/$OUTPUT_NAME -S
fi

# Check SAM file
if [ ! -f $OUTPUT ]; then
	echo "Unable to find CIRI output file!" >&2
	exit 9
fi
